version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - gocritic
    - gosec
    - makezero
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - testifylint
    - unconvert
    - wastedassign

  settings:
    errcheck:
      check-type-assertions: true

    govet:
      disable:
        - fieldalignment
        - shadow

    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx

  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - bodyclose
          - errcheck
          - gosec
          - noctx

issues:
  max-same-issues: 50
